### ISSUE TITLE
What is the difference?

### ISSUE THREAD

**Issue by gjf** [Magisk-Modules-Repo/CloudflareDNS4Magisk-IPv6#2]
What is the difference with [CloudflareDNS4Magisk](https://github.com/Magisk-Modules-Repo/CloudflareDNS4Magisk)?
The modules are the same absolutely the same except system.prop that presented in CloudflareDNS4Magisk only (and seems legit).

**Comment by xerta555** [comment]
> What is the difference with [CloudflareDNS4Magisk](https://github.com/Magisk-Modules-Repo/CloudflareDNS4Magisk)? The modules are the same absolutely the same except system.prop that presented in CloudflareDNS4Magisk only (and seems legit).

Fixed https://github.com/Magisk-Modules-Repo/CloudflareDNS4Magisk-IPv6/commit/e7cac41cc1ee91b31c491b8e56b3812cc6154294
